name: Java CI

on:
  push:
    branches:
      - 'dev/0.6-forge'
      - 'dev/0.7-forge'
      - 'dev/0.8'
      - 'dev/0.9'
      - 'dev/0.10.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Upload to Maven
        run: ./gradlew publish --stacktrace
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
